### ISSUE TITLE
Paragraphs starting with an equation puts attached text on new paragraph

### ISSUE THREAD

**Issue by jassler** [wviechtb/mathjaxr#13]
If I have a paragraph starting with `\mjseqn{}` or `\mjeqn{}{}`, everything after it is put in a new paragraph. As soon as I add a word in front of the macros, it works as intended.

```R
#' Note that \mjseqn{S} can also be empty.
#'
#' \mjseqn{S} should be on the same line as the rest of the sentence.
#'
#' Unlike Lexcel, ...
```

<img width="423" alt="Rendered math equation that displays the text after the equation on the next line." src="https://user-images.githubusercontent.com/24298790/149735464-ee2047a1-b796-45f5-a6eb-fa952e163597.png">

This is rendered in RStudio, both with the `mathjaxr::preview_rd` function as well as with `?myFunction` after doing a `devtools::install()`

**Comment by wviechtb** [comment]
This has already been fixed in the devel version.

**Comment by jassler** [comment]
Works, thanks!
