### ISSUE TITLE
Suggests vs Imports

### ISSUE THREAD

**Issue by bwiernik** [wviechtb/mathjaxr#8]
The documentation says that mathjaxr can be added to either Suggets or Imports, but I'm finding that when I run R CMD CHECK with mathjaxr in Suggests, it's erroring: https://github.com/easystats/effectsize/pull/341/checks?check_run_id=2697471853

Do you know if there is a way to get Suggests to work?

**Comment by wviechtb** [comment]
Indeed, just tried myself. If I recall correctly, this only raised a note before, but now it leads to an error. I have updated the instructions to describe only the `Imports` option.

**Comment by bwiernik** [comment]
Got it. Thanks! Sigh. I have some collaborators who are very averse to any `Imports` dependencies. Was hoping to be able to use mathjaxr with them but alas.

**Comment by wviechtb** [comment]
Totally get that. If `Suggests` was possible, it would be preferable, but I don't see at the moment how to make this happen.

**Comment by bwiernik** [comment]
What would be really nice is if R base adopted mathjaxr...
