### ISSUE TITLE
Package which is only available in source form, and may need compilation of C/C++/Fortran:   ‘mathjaxr’

### ISSUE THREAD

**Issue by davidfelip** [wviechtb/mathjaxr#9]
Hi everyone,

When trying to install packages for meta-analysis ("meta", or "metafor"),  the package ‘mathjaxr’ is pointed as a required dependency:

https://cran.rstudio.com/bin/windows/Rtools/ also installing the dependencies ‘mathjaxr’ (...)

But, it fails with the following explanation:
" Package which is only available in source form, and may need compilation of C/C++/Fortran: ‘mathjaxr’ "

If anybody can help? Thanks in advance!
David

**Comment by wviechtb** [comment]
You do not need Rtools to install metafor, meta, or mathjaxr. I just tried installing metafor and meta under Windows (R version 4.1.0) and both installed with any problems, installing mathjaxr along the way.

**Comment by iagogv3** [comment]
Related current discussion on R-devel: https://stat.ethz.ch/pipermail/r-devel/2025-May/084033.html

Let's see as it is solved...
